#!/bin/sh
# stash unstaged changes, run verify task and restore stashed files
PATH="/usr/local/bin:$PATH"

NAME=$(git branch | grep '*' | sed 's/* //')

# don't run on rebase
if [ $NAME != '(no branch)' ]
then
  git stash -q --keep-index
  grunt verify

  RETVAL=$?

  if [ $RETVAL -ne 0 ]
  then
  	git stash pop -q
    exit 1
  fi

  git stash pop -q
fi
